data_dir: ../data/azure
model_dir: ../model_cased/azure
batch_size: 10
batch_size_test: 1000
epochs: 400
pos_weight: 1
lr: 0.0001
momentum: 0.9
topn_relevant_keywords: 1000
frac_relevant_keywords: 0.25
w_marg_contr: 0.3
w_count: 0.2
w_sim : 0.5
num_workers : 2
weight_decay : 0.01
model_name : dkleczek/bert-base-polish-cased-v1